// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXQEzESMRkke7abeQQfSp1ANhW_wIbOkI',
    appId: '1:182075701458:web:1e467355c5755d4a39d50b',
    messagingSenderId: '182075701458',
    projectId: 'habitflow-baee5',
    authDomain: 'habitflow-baee5.firebaseapp.com',
    storageBucket: 'habitflow-baee5.firebasestorage.app',
    measurementId: 'G-0B9C9SYLLK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUrK8Q7VHv9b8zx4fzQXfP_d5dTa3CDFM',
    appId: '1:182075701458:android:d2b4f5ef1b013bdd39d50b',
    messagingSenderId: '182075701458',
    projectId: 'habitflow-baee5',
    storageBucket: 'habitflow-baee5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIk2raSt26UjnU0PpJ0zSksuX7kiiWgWo',
    appId: '1:182075701458:ios:49300991e414f74239d50b',
    messagingSenderId: '182075701458',
    projectId: 'habitflow-baee5',
    storageBucket: 'habitflow-baee5.firebasestorage.app',
    iosBundleId: 'com.example.habitflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIk2raSt26UjnU0PpJ0zSksuX7kiiWgWo',
    appId: '1:182075701458:ios:49300991e414f74239d50b',
    messagingSenderId: '182075701458',
    projectId: 'habitflow-baee5',
    storageBucket: 'habitflow-baee5.firebasestorage.app',
    iosBundleId: 'com.example.habitflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXQEzESMRkke7abeQQfSp1ANhW_wIbOkI',
    appId: '1:182075701458:web:c1778163a9f58d7b39d50b',
    messagingSenderId: '182075701458',
    projectId: 'habitflow-baee5',
    authDomain: 'habitflow-baee5.firebaseapp.com',
    storageBucket: 'habitflow-baee5.firebasestorage.app',
    measurementId: 'G-6RYD7RLEQ9',
  );
}
